### ISSUE TITLE
指定下载

### ISSUE THREAD

**Issue by NonCheng** [Aloxaf/exloli#125]
请问能下载指定本子

给出链接或者本子完整名称来匹配
而不是匹配随机性很强的tag

**Comment by Aloxaf** [comment]
可以用 `exloli upload 本子地址` 来下载指定本子

**Comment by NonCheng** [comment]
好的 谢谢啦

（不能在tg上通过bot指令来交互吗

**Comment by Aloxaf** [comment]
> 好的 谢谢啦
> 
> （不能在tg上通过bot指令来交互吗

好主意！这样确实方便多了……

**Comment by Aloxaf** [comment]
已实现于 71db9b51b33a187a3b278d22dea514d1ff7d02c3
